Disable `fedora/eln/unprivileged` container building for now
The build fails with:

    Transaction failed: Signature verification failed.
    OpenPGP check for package "shadow-utils-2:4.19.0-6.eln154.x86_64"
    (/var/cache/libdnf5/eln-baseos-a1f2cae0598f9cea/packages/shadow-utils-4.19.0-6.eln154.x86_64.rpm)
    from repo "eln-baseos" has failed: Import of the key didn't help,
    wrong key?
    Error: building at STEP "RUN <<EOF": while running runtime: exit status 1

Note from yselkowitz:

    this seems to be a timing issue with the F44 branching.  some ELN
    builds are signed with only the F45 key (this switch happens right
    before branching) but fedora-repos hasn't been updated yet because
    branching was delayed a day due to other issues.

Let's disable it for now to unblock testing & merging. Btw, it seems the
container is not used by any test.