Prevent building container images for installed dependencies in Image Mode
The original code was building container images for:

* presence checks of packages
* already installed packages on the system

Improve this by:

* Limiting presence checks to building container images only when necessary
* Performing presence checks on the booted system and preventing container
  image builds when dependencies are already satisfied

Add missing test coverage using Testing Farm's CentOS Stream 9 bootc
qcow2 image available at http://artifacts.dev.testing-farm.io/images.
The tests cover cases for both root and non-root users and include the
use case for skipping the prepare step needed for the RHEL AI use case.

Also improve the Bootc.check_presence function:

* Remove special handling for a single FileSystemPath installable
* Remove matching of "package ... is not installed", which appears to
  be an rpm-ostree leftover
* Handle all installables properly by matching the output of "rpm -qf PATH",
  e.g.:

```
rpm -q --whatprovides /etc/whatever
error: file /etc/whatever: No such file or directory
```

Resolves #3791

Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>