Re-enable Rawhide tests (#4017)
Tracking and fixing the remaining rawhide tests that were disabled in
https://github.com/teemtee/tmt/pull/3869

What is being fixed:
- [x] pip install issues: Was blocked by `cffi` release
- [x] New pickling issue `/tests/unit/with-development-packages/basic`
With python 3.14 the pickling started to fail again specifically with
    ```
FAILED test_base.py::test_pickleable_tree - TypeError: cannot pickle
'itertools.count' object
    when serializing dict item '_child_id_counter'
    when serializing tmt.log.Logger state
    when serializing tmt.log.Logger object
    when serializing dict item '_logger'
    when serializing tmt.base.Tree state
    when serializing tmt.base.Tree object
    ```
The logger is not really useful to be pickled so it is just removed and
re-created. Would be useful to generalize this a bit more :thinking:
- [x] New issues running with toolbox container: To be investigated,
probably the same as the pip install issue (it seems like it was)

---------

Signed-off-by: Cristian Le <git@lecris.dev>